// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgg0VgAo73nxCbuvt0NI7maxR10PHAjA',
    appId: '1:620687590211:android:18cc01c35c3720f1a765f6',
    messagingSenderId: '620687590211',
    projectId: 'flutter-weather-app-e6f8d',
    databaseURL: 'https://flutter-weather-app-e6f8d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-weather-app-e6f8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Lhx9KvtFoQEHL_SaGqdR9f8fDWxAb3Y',
    appId: '1:620687590211:ios:c106e15654095f81a765f6',
    messagingSenderId: '620687590211',
    projectId: 'flutter-weather-app-e6f8d',
    databaseURL: 'https://flutter-weather-app-e6f8d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-weather-app-e6f8d.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

}